### ISSUE TITLE
Storybook is broken

### ISSUE THREAD

**Issue by biels** [Fundflow/apollo-redux-form#51]
After a clean clone, the stries cannot find ../lib/.. which I guess it has been removed in a refactor. Even after renaming it it doesn't work. Says 'unexpected token export'. Maybe the typescript processor is not applied to stories?

**Comment by mstn** [comment]
Hi @biels thanks for your issue.

Yes, stories are in javascript and typescript processor is not applied. We have an open issue for that https://github.com/Fundflow/apollo-redux-form/issues/41

You should run `npm run compile` before running stories. In this way the source is compiled and the lib directory is created. I will add a note to the README.md
