### ISSUE TITLE
Form state made only of values that matched actual form fields

### ISSUE THREAD

**Issue by mstn** [Fundflow/apollo-redux-form#8]
Now, ReduxForm sets the initial state of a form to arbitrary values. This is a problem with Apollo. We need to prefilter (recursively) initialValues.

See more
https://github.com/erikras/redux-form/issues/1453

**Comment by tommyalvarez** [comment]
@mstn What about a non-apollo solution? I also need to prune arbitrary init values that are not related to the actual fields in the form

**Comment by mstn** [comment]
@tommyalvarez thanks for your question. We are (slowly) working on a version to decouple form building from Apollo. Form generation is actually independent from Apollo. If you look into the code, you will find a function `buildForm` that is used by `apolloForm`, but it is independent from Apollo stuff.
